//
// This is a basic typescript example of how to include the TINAD sdk.
// Change the displayMode to change the way your notifications appear,
// and consult the docs and the example configuration object at the bottom
// to see what other configuration settings are available.

import { 
  configureTinad, 
  generateDefaultConfiguration, 
  getCurrentConfiguration, 
  SDKConfiguration
} from '@this-is-not-a-drill/vanillajs-sdk';

import environment from './environment';

console.log('Configurating TINAD SDK...');

const newConfig = generateDefaultConfiguration();

// Put your values into the configuration.
newConfig.api.endpoint = environment.API_ENDPOINT;
newConfig.api.key = environment.API_KEY;

// You can try changing this to 'modal', 'inline', or 'banner'.
newConfig.api.displayMode = 'toast';

configureTinad(newConfig);

// Uncomment these to see what TINAD has for its current configuration.
// const currentConfig = getCurrentConfiguration();
// console.log(`Current TINAD config: ${JSON.stringify(currentConfig,null,2)}`);

console.log('TINAD configuration complete.');

const resetButton = document.getElementById('reset-notifications');

// When you reconfigure TINAD with the same configuration a second
// time, this has the effect of resetting the views for the current
// userId (as well as stopping any notification display in progress).

resetButton.onclick = function() {
  console.log ('Resetting views'); 
  const currentConfig = getCurrentConfiguration();
  configureTinad(currentConfig);
};

// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=--=-
// This is an example SDKConfiguration object with some basicdefaults.
//  Depending on the displayMode you choose, you will actually
// only need the property that's relevant to it, e.g.  if you choose
// displayMode: 'toast', then you actually only need to include the
// 'toast' property. Add your API key in the api block.
// If you don't set a specific user id, the SDK will
// autogenerate one for you.
// See the docs at docs.this-is-not-a-drill.com for more.
// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=--=-
/*
{
    api: {
      displayMode : 'toast',
      userId: <autogenerated>, // Override this in your code or accept the autogenerated user id
      key: '',                 // Enter your API key in this property
      endpoint: 'https://api.this-is-not-a-drill.com',
      environments: [ 'Development' ],
      domains: [],
    },
    toast: {
      position: 'top-right',
      duration: 5000,
    },
    modal: {
      confirmButtonLabel: 'OK',
      show: {
        confirm: true,
        dismiss: true,
      },
    },
    inline: {
      target: {
        outer: 'tinad-inline-container',
        content: 'tinad-inline-content',
        confirm: 'tinad-inline-confirm',
        dismiss: 'tinad-inline-dismiss',
      },
      show: {
        confirm: true,
        dismiss: true,
      },
    },
    banner: {
      duration: 5000,
      target: {
        useDefaults: true,
      },
      show: {
        dismiss: true,
      },
    },
  };
*/
